name: GitHub-Profile-3D-Contrib-with-mkdocs
description: Generate profile 3D Contributions with mkdocs
author: yoshi389111, sas08

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'box'
  color: 'green'
